// ui/src/components/Tiptap/index.vue
<template>
    <div>
        <div class="button" ref="buttonPanel">
            <button @click="editor.chain().focus().toggleBold().run()">Bold</button>
            <button @click="editor.chain().focus().toggleItalic().run()">Italic</button>
            <button @click="editor.chain().focus().toggleUnderline().run()">Underline</button>
            <button @click="styleColorRed">Red</button>
            <button @click="styleColorBlue">Blue</button>
            <button @click="editor.chain().focus().setHorizontalRule().run()">Horizontal</button>
            <button @click="styleClearStyle">Clear</button>
        </div>
        <editor-content :editor="editor" />
    </div>
</template>
<script>
    import { Editor, EditorContent } from "@tiptap/vue-2";
    import StarterKit from "@tiptap/starter-kit";
    import Paragraph from "@tiptap/extension-paragraph";
    import TextStyle from "@tiptap/extension-text-style";
    import { Color } from "@tiptap/extension-color";
    import Bold from "@tiptap/extension-bold";
    import Italic from "@tiptap/extension-italic";
    import Underline from "@tiptap/extension-underline";
    import HorizontalRule from "@tiptap/extension-horizontal-rule";
    export default {
        props: {
            content: {
                type: String,
                default: "",
            },
        },
        components: {
            EditorContent,
        },
        data() {
            return {
                editor: null,
            };
        },
        mounted() {
            this.editor = new Editor({
                content: this.content,
                extensions: [StarterKit, Paragraph, Italic, Underline, TextStyle, Bold, Color, HorizontalRule],
            });
            this.eventCreateObserver();
            this.eventCreateScrollListener();
        },
        methods: {
            getHTML() {
                return this.editor.getHTML();
            },
            styleClearStyle() {
                this.editor.chain().focus().unsetColor().run();
                this.editor.chain().focus().unsetBold().run();
                this.editor.chain().focus().unsetUnderline().run();
                this.editor.chain().focus().unsetItalic().run();
            },
            styleColorRed() {
                this.editor.chain().focus().setColor("#F98181").run();
                this.editor.chain().focus().toggleBold().run();
            },
            styleColorBlue() {
                this.editor.chain().focus().setColor("#70CFF8").run();
                this.editor.chain().focus().toggleBold().run();
            },
            eventCreateObserver() {
                const observer = new IntersectionObserver(this.eventHandlerIntersect, {
                    root: null,
                    rootMargin: "0px",
                    threshold: 0,
                });
                observer.observe(this.$refs.buttonPanel);
            },
            eventCreateScrollListener() {
                window.addEventListener("scroll", this.eventHandlerScroll, true);
            },
            eventHandlerIntersect(entries) {
                entries.forEach((entry) => {
                    if (!entry.isIntersecting) {
                        if (typeof this.$refs.buttonPanel !== "undefined" && !this.$refs.buttonPanel.classList.contains("fixed")) {
                            this.$refs.buttonPanel.classList.add("fixed");
                        }
                    }
                });
            },
            eventHandlerScroll(e) {
                if (e.target.scrollTop === 0) {
                    if (typeof this.$refs.buttonPanel !== "undefined") {
                        this.$refs.buttonPanel.classList.remove("fixed");
                    }
                }
            },
        },
        beforeDestroy() {
            this.editor.destroy();
        },
    };
</script>
<style lang="scss">
    .button {
        button {
            padding: 4px 10px;
        }
        button + button {
            margin-left: 10px;
        }
        &.fixed {
            position: fixed;
            top: 10px;
            z-index: 999;
        }
    }
</style>

// ui-react-ts/src/views/components/tiptap/index.tsx
import React, { useEffect, useRef } from "react";
import { useEditor, EditorContent } from "@tiptap/react";
import StarterKit from "@tiptap/starter-kit";
import Bold from "@tiptap/extension-bold";
import Italic from "@tiptap/extension-italic";
import Underline from "@tiptap/extension-underline";
import HorizontalRule from "@tiptap/extension-horizontal-rule";
import Paragraph from "@tiptap/extension-paragraph";
import TextStyle from "@tiptap/extension-text-style";
import { Color } from "@tiptap/extension-color";
import { Button, Space, Row } from "antd";
import { BoldOutlined, ItalicOutlined, UnderlineOutlined, DashOutlined, BgColorsOutlined, ClearOutlined } from "@ant-design/icons";
import "./index.scss";
import debounce from "lodash.debounce";

interface props {
    content: string;
    onChange: (content: string) => void;
    onSelect?: (content: string) => void;
}
const extensions = [StarterKit, Bold, Italic, Underline, HorizontalRule, Color, Paragraph, TextStyle];
const Tiptap: React.FC<props> = ({ content, onChange, onSelect }) => {
    const refPanel = useRef<HTMLDivElement>(null);
    const editor = useEditor({
        extensions,
        content,
        onUpdate({ editor }) {
            if (onChange) {
                onChange(editor.getHTML());
            }
        },
    });
    const setColorRed = () => {
        editor?.chain().focus().setColor("#F98181").run();
        editor?.chain().focus().setBold().run();
    };
    const setColorBlue = () => {
        editor?.chain().focus().setColor("#70CFF8").run();
        editor?.chain().focus().setBold().run();
    };
    const clearStyle = () => {
        editor?.chain().focus().unsetColor().run();
        editor?.chain().focus().unsetBold().run();
        editor?.chain().focus().unsetUnderline().run();
        editor?.chain().focus().unsetItalic().run();
    };
    const observer = new IntersectionObserver(
        (entries) => {
            entries.forEach((entry) => {
                if (!entry.isIntersecting) {
                    if (refPanel.current && !refPanel.current.classList.contains("fixed")) {
                        refPanel.current.classList.add("fixed");
                    }
                }
            });
        },
        {
            root: null,
            rootMargin: "0px",
            threshold: 0,
        }
    );
    if (refPanel.current) observer.observe(refPanel.current);

    const eventHandlerScroll = (e: any) => {
        if (e.target.scrollTop === 0) {
            if (refPanel.current) {
                refPanel.current.classList.remove("fixed");
            }
        }
    };

    useEffect(() => {
        if (editor && content !== editor.getHTML()) {
            editor.commands.setContent(content);
        }
    }, [content, editor]); // 挂载、移除、内容变化
    useEffect(() => {
        if (!editor) return;
        const handleSelectionUpdate = debounce(() => {
            const { from, to } = editor.state.selection;
            const selectedText = editor.state.doc.textBetween(from, to, " ");
            console.log("Selected text:", selectedText);
            onSelect?.(selectedText);
        }, 500);
        // 监听选区更新事件
        editor.on("selectionUpdate", handleSelectionUpdate);
        // 清理事件监听器
        return () => {
            editor.off("selectionUpdate", handleSelectionUpdate);
        };
    }, [editor]); // 挂载与移除

    window.addEventListener("scroll", eventHandlerScroll, true);

    console.log("Tiptap Loaded");

    return (
        <div>
            <Row>
                <Space ref={refPanel} className="panel" style={{ marginBottom: "10px" }}>
                    {/* prettier-ignore */}
                    <Button onClick={() => { editor?.chain().focus().toggleBold().run() }}><BoldOutlined />Bold</Button>
                    {/* prettier-ignore */}
                    <Button onClick={() => { editor?.chain().focus().toggleItalic().run() }}><ItalicOutlined />Italic</Button>
                    {/* prettier-ignore */}
                    <Button onClick={() => { editor?.chain().focus().toggleUnderline().run() }}><UnderlineOutlined />Underline</Button>
                    {/* prettier-ignore */}
                    <Button onClick={() => { editor?.chain().focus().setHorizontalRule().run() }}><DashOutlined />Horizontal</Button>
                    {/* prettier-ignore */}
                    <Button onClick={setColorRed}><BgColorsOutlined style={{color: "#F98181"}} />Red</Button>
                    {/* prettier-ignore */}
                    <Button onClick={setColorBlue}><BgColorsOutlined style={{color: "#70CFF8"}} />Blue</Button>
                    {/* prettier-ignore */}
                    <Button onClick={clearStyle}><ClearOutlined />Clear</Button>
                </Space>
            </Row>
            <Row>
                <EditorContent editor={editor} style={{ width: "100%" }} />
            </Row>
        </div>
    );
};

export default Tiptap;
